"""
Scientific Hypertrophy Trainer - Learning Center v3.1 (FIXED)
- Fixed: Indentation errors
- Fixed: Database content loading
"""

from PyQt6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QLabel, QListWidget, QFrame,
    QPushButton, QTextEdit, QScrollArea, QTabWidget, QGridLayout, QProgressBar
)
from PyQt6.QtCore import Qt

KNOWLEDGE_DB = {
    "Hypertrophy Mechanisms": {
        "Mechanical Tension": "The primary driver of hypertrophy. It is the force generated by muscle fibers to resist a load.",
        "Metabolic Stress": "Secondary driver. Cell swelling and metabolite accumulation.",
        "Muscle Damage": "Often overrated. Excessive damage competes with recovery."
    },
    "Volume & Frequency": {
        "MEV (Min Effective Volume)": "Minimum sets/week to make gains (approx 6-10).",
        "MRV (Max Recoverable Volume)": "Volume ceiling before regression (approx 20+).",
        "Frequency": "2-3x per week is generally superior to 1x."
    },
    "Intensity": {
        "RIR": "Reps In Reserve. 1-3 RIR is the sweet spot for growth/fatigue ratio.",
        "Effective Reps": "Only the last 5 reps before failure recruit high-threshold fibers."
    },
    "Recovery": {
        "Sleep": "Deep sleep = Growth Hormone. REM = Neural recovery.",
        "Deloads": "Planned volume reduction to dissipate fatigue."
    }
}

class LearningWidget(QWidget):
    def __init__(self, db_manager, user_manager):
        super().__init__()
        self.db = db_manager
        self.user_manager = user_manager
        self.init_ui()
    
    def init_ui(self):
        main_layout = QVBoxLayout(self)
        main_layout.setContentsMargins(30, 30, 30, 30)
        
        header = QLabel("Knowledge Base & Education")
        header.setStyleSheet("font-size: 28px; font-weight: 800; color: #89b4fa;")
        main_layout.addWidget(header)
        
        self.tabs = QTabWidget()
        self.tabs.addTab(self.create_skill_tab(), "🧠 My Skill Profile")
        self.tabs.addTab(self.create_library_tab(), "📚 Concept Library")
        self.tabs.addTab(self.create_mistakes_tab(), "⚠️ Mistake Review")
        
        main_layout.addWidget(self.tabs)

    def create_skill_tab(self):
        tab = QWidget()
        layout = QVBoxLayout(tab)
        layout.setContentsMargins(20, 20, 20, 20)
        
        info = QLabel("AI Confidence Scores based on your assessment history.")
        info.setStyleSheet("color: #a6adc8; font-style: italic; margin-bottom: 20px;")
        layout.addWidget(info)
        
        self.skill_container = QFrame()
        self.skill_container.setStyleSheet("background-color: #262639; border-radius: 12px; padding: 20px;")
        self.skill_layout = QVBoxLayout(self.skill_container)
        self.skill_layout.setSpacing(20)
        
        layout.addWidget(self.skill_container)
        layout.addStretch()
        return tab

    def create_library_tab(self):
        tab = QWidget()
        layout = QHBoxLayout(tab)
        layout.setContentsMargins(0, 20, 0, 0)
        
        topic_frame = QFrame()
        topic_frame.setFixedWidth(250)
        topic_frame.setStyleSheet("background: #181825; border-radius: 8px;")
        t_layout = QVBoxLayout(topic_frame)
        
        self.topic_list = QListWidget()
        self.topic_list.setStyleSheet("border: none; background: transparent; color: #cdd6f4;")
        for category in KNOWLEDGE_DB.keys():
            self.topic_list.addItem(category)
        self.topic_list.currentItemChanged.connect(self.load_topic_content)
        
        t_layout.addWidget(self.topic_list)
        layout.addWidget(topic_frame)
        
        content_frame = QFrame()
        content_frame.setStyleSheet("background: #1e1e2e;")
        c_layout = QVBoxLayout(content_frame)
        
        self.lbl_topic = QLabel("Select Topic")
        self.lbl_topic.setStyleSheet("font-size: 24px; color: #fab387; font-weight: bold;")
        self.txt_content = QTextEdit()
        self.txt_content.setReadOnly(True)
        self.txt_content.setStyleSheet("background: #262639; border-radius: 8px; padding: 15px; font-size: 14px; color: #cdd6f4;")
        
        c_layout.addWidget(self.lbl_topic)
        c_layout.addWidget(self.txt_content)
        layout.addWidget(content_frame)
        return tab

    def create_mistakes_tab(self):
        tab = QWidget()
        layout = QVBoxLayout(tab)
        
        self.mistakes_area = QScrollArea()
        self.mistakes_area.setWidgetResizable(True)
        self.mistakes_area.setStyleSheet("border: none; background: transparent;")
        
        self.mistakes_container = QWidget()
        self.mistakes_layout = QVBoxLayout(self.mistakes_container)
        self.mistakes_layout.setAlignment(Qt.AlignmentFlag.AlignTop)
        
        self.mistakes_area.setWidget(self.mistakes_container)
        layout.addWidget(self.mistakes_area)
        return tab

    def refresh_data(self):
        self.load_skills()
        self.load_mistakes()

    def load_skills(self):
        while self.skill_layout.count():
            child = self.skill_layout.takeAt(0)
            if child.widget(): child.widget().deleteLater()
            
        user = self.user_manager.get_current_user()
        if not user: return
        
        profile = self.db.get_user_ml_profile(user['id'])
        skills = [
            ("Training Literacy", profile.get('training_literacy_index', 0.5)),
            ("Recovery IQ", profile.get('recovery_knowledge', 0.5)),
            ("Technique", profile.get('technique_score', 0.5))
        ]
        
        for name, score in skills:
            self.add_skill_bar(name, score)

    def add_skill_bar(self, name, score):
        pct = int(score * 100)
        lbl = QLabel(f"{name}: {pct}%")
        lbl.setStyleSheet("color: white; font-weight: bold;")
        bar = QProgressBar()
        bar.setValue(pct)
        bar.setStyleSheet(f"QProgressBar::chunk {{ background-color: {'#a6e3a1' if pct > 70 else '#f9e2af'}; }}")
        self.skill_layout.addWidget(lbl)
        self.skill_layout.addWidget(bar)

    def load_topic_content(self, item):
        if not item: return
        cat = item.text()
        self.lbl_topic.setText(cat)
        html = ""
        for term, desc in KNOWLEDGE_DB.get(cat, {}).items():
            html += f"<h3 style='color: #89b4fa;'>{term}</h3><p>{desc}</p><br>"
        self.txt_content.setHtml(html)

    def load_mistakes(self):
        while self.mistakes_layout.count():
            child = self.mistakes_layout.takeAt(0)
            if child.widget(): child.widget().deleteLater()
            
        user = self.user_manager.get_current_user()
        if not user: return
        
        assessments = self.db.get_user_assessments(user['id'])
        found = False
        for a in assessments:
            answers = self.db.get_assessment_answers(a['id'])
            for ans in answers:
                if not ans['is_correct']:
                    self.add_mistake_card(ans)
                    found = True
        
        if not found:
            self.mistakes_layout.addWidget(QLabel("No mistakes found. Good job!"))

    def add_mistake_card(self, answer_data):
        card = QFrame()
        card.setStyleSheet("background: #262639; border-radius: 8px; border-left: 4px solid #f38ba8;")
        layout = QVBoxLayout(card)
        
        q_text = answer_data.get('question_text') or f"Question ID: {answer_data.get('question_id')}"
        layout.addWidget(QLabel(f"<b>Question:</b> {q_text}"))
        
        hbox = QHBoxLayout()
        wrong = QLabel(f"❌ You: {answer_data['user_answer']}")
        wrong.setStyleSheet("color: #f38ba8;")
        right = QLabel(f"✅ Correct: {answer_data['correct_answer']}")
        right.setStyleSheet("color: #a6e3a1;")
        
        hbox.addWidget(wrong)
        hbox.addWidget(right)
        layout.addLayout(hbox)
        
        self.mistakes_layout.addWidget(card)